import { chromium } from "playwright-core";
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const john = await browser.newContext({ viewport: { width: 1280, height: 800 } });
let page = await john.newPage();
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.getByLabel("Email").fill("john@example.com");
await page.getByLabel("Password").fill("Demo1234!");
await page.getByRole("button", { name: "Log in", exact: true }).click();
await page.waitForURL((u) => !u.pathname.startsWith("/login"), { timeout: 25000 });
await page.goto(`${BASE}/account`, { waitUntil: "networkidle" });
await page.getByRole("tab", { name: "Orders" }).click();
await page.waitForLoadState("networkidle");
let t = await page.evaluate(() => document.body.innerText);
console.log("=== ACCOUNT ORDERS TAB ===");
console.log(t.slice(t.indexOf("Order History"), t.indexOf("Saved Addresses") > 0 ? t.indexOf("Saved Addresses") : t.indexOf("Order History") + 700));
await page.goto(`${BASE}/checkout/success?order=ORD-2026-004`, { waitUntil: "networkidle" });
t = await page.evaluate(() => document.body.innerText);
console.log("=== CONFIRMATION ===");
console.log(t.slice(t.indexOf("Order Confirmed"), t.indexOf("Order Confirmed") + 500));
await browser.close();
