import { chromium } from "playwright-core";
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.getByLabel("Email").fill("admin@luxestore.com");
await page.getByLabel("Password").fill("Admin1234!");
await page.getByRole("button", { name: "Log in", exact: true }).click();
await page.waitForURL((u) => !u.pathname.startsWith("/login"), { timeout: 25000 });
await page.goto(`${BASE}/admin/orders`, { waitUntil: "networkidle" });
await page.getByRole("link", { name: "ORD-2026-004" }).click();
await page.waitForURL(/\/admin\/orders\/(?!ORD)/, { timeout: 10000 });
await page.waitForLoadState("networkidle");
await page.waitForTimeout(500);
const body = await page.evaluate(() => document.body.innerText);
const main = body.slice(body.indexOf("← Orders") >= 0 ? body.indexOf("← Orders") : 0, body.indexOf("LUXE\nCurated"));
console.log("URL:", page.url().slice(-20));
console.log(main.slice(0, 1200));
await browser.close();
